---
title: "Climate footprint of Danish Consumption"
author: 
  - Akkoyun, Furkan[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{english}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== FOOTNOTES ============================== -->
<!-- ======================================================================= -->
[^1]: 20080377, [Github Repo](https://github.com/furkanakkoyunn/20080377)


# Introduction

Global climate transformation is an urgent global challenge that needs a complete understanding of the diverse factors contributing to it. These include the consumption customs of different countries and economies. Denmark is no anomaly among developed countries with a high average of living. The climate footprint is the total share of greenhouse gases ejected throughout the life cycle of a product or service, including production, transport, and use. The climate footprint of Danish consumption is an important area of research. Danish consumption patterns are discussed over time, in several countries and economies, in several types of use, and in several industries. Concentrating on the roots of emissions and the causes for emissions in various sectors, this article examines how time, economies, types of use, and industries affect the environmental footprint of Danish consumption. An examination of the climate footprint of Danish consumption can shed light on the relationship between consumption, production, and greenhouse gas emissions. It can also supply insights into the environmental impact of consumption options in Denmark and beyond. The Data set used in the research was taken from Statistics Denmark.I chose the Climate footprint of Danish Consumption by time, countries/economies, types of use and industries Data set that has 153 observations with 13 variables including categorical industries (Origin of emissions) A Agriculture, forestry and fishing, B Mining and quarrying, C Manufacturing, D_E Utility services, F Construction, G_I Trade and transport etc., J Information and communication, K Financial and insurance, LA Real estate activities and renting of non-residential buildings, LB Dwellings, M_N Other business services, O_Q Public administration, education and health, R_S Arts, entertainment and other services. In the end, I formulated my question: "How do economies, types of use, and industries affect the climate footprint of Danish consumption in terms of greenhouse gas emissions? Then I focused more specifically on the articles related to my research question for the project.

## Literature Review

Climate footprint calculations are carried out for different activities such as transportation, energy consumption, water use, production and consumption of products. As a result of climate footprint calculations, people can take steps to reduce their carbon footprints and contribute to the fight against climate change. Studies on climate change and climate footprint and increased awareness make people more sensitive to environmental issues. Individuals and organizations need to take action to solve this problem. For a sustainable future, it is important to reduce greenhouse gas emissions, switch to renewable energy sources and protect natural resources.

@batini:2020 propose a comprehensive package of pricing and sectoral-based mitigation instruments for Denmark and discuss fiscal measures for mitigating agricultural emissions and recommends the use of revenue-neutral feebate schemes to strengthen mitigation incentives, particularly for transportation and agriculture, fisheries and forestry, though these schemes could also be applied more widely. @wackernagel:1999 The Ecological Footprint is one of those indicators that try to capture a broad picture of humanity's demand on natural resources, following the principle of consumer responsibility. @jack:2021 makes an original contribution using storytelling, a step in the direction of increasing empathy and compassion for the various carbon footprint cohorts and working toward socially and environmentally sustainable futures. @antal:2021 different measures, definitions and databases are used. The environmental indicators range from production-based energy and emission accounts to consumption-based carbon-, material- and ecological footprints. @dubois:2019 highlights the need for climate policies that target household consumption and behavioral decisions as key components of low-carbon futures. @salo:2019 authors found that while carbon footprint calculators can be effective tools for promoting sustainable household consumption practices, there are limitations to their use, such as incomplete data and language barriers. Overall, the research highlights the potential benefits and limitations of carbon footprint calculators in promoting sustainable household consumption practices.

\newpage
# References {#references}
<div id="refs"></div>

